library(tidyverse)

gen_filename_simulate_data <- function (min_entry_size, max_entry_size,
                                        entry_correlation_sd,target_num_rows_data,
                                        include_path = TRUE, include_extension = TRUE
){
  if (include_path){rel_path <- 'simulation_study/simulation_data/'} else {rel_path <- ''}
  if (include_extension){end_str <- '.csv'} else {end_str <- ''}
  paste0(rel_path, 'entrysize_', min_entry_size, '_', max_entry_size,
         '_entry_corr', entry_correlation_sd,'_rows_', target_num_rows_data, end_str
  )
}

#' Generate file name based on Stan fit parameters
#' 
#' @param min_entry_size, int
#' @param max_entry_size, int
#' @param entry_correlation_sd, int
#' @param num_line_rows, int or empty
#' @param num_container_rows, int or empty
#' @param include_path, bool, true (default) sets file path to simulation_study/simulation_stan_results
#' @param include_extension, bool, true (default) sets file extension to ".Rda", otherwise no extension
#' @return file path or file name based on input parameters
gen_filename_stanfit_simulated_data <- function (min_entry_size, max_entry_size,
                                                 entry_correlation_sd, num_line_rows, num_container_rows,
                                                 index = NULL,
                                                 include_path = TRUE, include_extension = TRUE){
  
  # set file path
  rel_path = file.path("simulation_study", "simulation_stan_results")
  # optional index number
  ind_str = ifelse(is.null(index),"",paste0("number_", index))
  # set extension
  end_str = ifelse(include_extension, ".Rda", "")
  # if number of line or container rows are empty, set to zero
  num_line_rows = ifelse(is_empty(num_line_rows), 0, num_line_rows)
  num_container_rows = ifelse(is_empty(num_container_rows), 0, num_container_rows)
  
  # return file name
  fn = paste0("entrysize_", min_entry_size,"_",max_entry_size,
         "_corr_sd_",entry_correlation_sd,"_num_line_",num_line_rows,"_num_container_",num_container_rows,
         "_fit_summary",ind_str,end_str)
  
  ifelse(include_path, file.path(rel_path, fn), fn)
}


#' Extract parameters from file name
#' 
#' Extract parameters from file name generated by gen_filename_stanfit_simulated_data()
#' @param filename, string with the filename (with or without file path and extension)
#' @return list of parameter values
extract_params_stanfit_simulated_data = function(filename){
  params = basename(filename)
  params = str_split(params, pattern = "_")[[1]]
  
  if(length(params)!= 14){
    message(paste(filename, "not in correct format"))
    return()
  }

  matching = c(check_string(params[1], "entrysize"),
               check_string(params[4], "corr"),
               check_string(params[5], "sd"),
               check_string(params[7], "num"),
               check_string(params[8], "line"),
               check_string(params[10], "num"),
               check_string(params[11], "container"),
               check_string(params[13], "fit"),
               check_string(params[14], "summary.Rda"))

  if(!all(matching)){
    message(paste(filename, "not in correct format"))
    return()
  }
  
  list(min_entry_size = as.numeric(params[2]),
       max_entry_size = as.numeric(params[3]),
       entry_correlation_sd = as.numeric(params[6]),
       num_line_rows = as.numeric(params[9]),
       num_container_rows = as.numeric(params[12]))
}


#' Check string
#' 
#' Checks whether two strings are the same
#' 
#' @param string 1
#' @param string 2
#' @return TRUE if the strings are the same, FALSE if they're not
check_string = function(string1, string2){
  output = TRUE
  if(string1 != string2){
    message(paste(string1, "expected to be", string2))
    output = FALSE
  }
  output
}
